% ../.common/high-school-notebook.cls
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{../.common/high-school-notebook}[2024/01/28 High School Notebook Class]

\LoadClass{article}

\RequirePackage[a4paper, margin=25mm]{geometry}
\RequirePackage[italian]{babel}
\RequirePackage{hyperref}
\RequirePackage{amsmath}
\RequirePackage{pgfplots}
\RequirePackage{graphicx}
\RequirePackage{float}
\RequirePackage{amsfonts}

% \pgfplotsset{compat=1.18}
\usetikzlibrary{intersections}


\setlength{\parindent}{0pt}

